apiVersion: v1
kind: Service
metadata:
  name: fnbmeshclient
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # Port for LB, AWS ELB allow port 80 only  
      targetPort: 8081 # Port for Target Endpoint
  selector:
    app: fnbmeshclient
    